#!/usr/bin/env python3
"""Comps: rendered from the contract, generated by a model, and measured after.

Three separable jobs, and keeping them separate is what makes this trustworthy:

  1. RENDER   A comp drawn deterministically from `.deluxui/design.contract.yaml`.
              Needs no model, no key and no network, so it is always available.
              It is conformant by construction -- every fill is a declared role,
              every size a declared rung, every radius a declared value -- which
              means it cannot be the thing that drifts.
  2. GENERATE A raster from an image model, when one is reachable. The prompt is
              built FROM the contract rather than from an adjective, and the
              result carries its prompt, provider and the contract's hash inside
              the file.
  3. VERIFY   The generated raster measured back against the contract it claims to
              express. This is the half a generator alone never does: a model
              returns a beautiful image in a palette nobody declared, somebody
              approves it, and the built screen is then judged against a comp that
              was never the system. Drift is reported per role, in numbers.

    ux_image.py brief --write [--surface "property detail"] [--options 3]
    ux_image.py render BRIEF.yaml [--out .deluxui/comps]
    ux_image.py generate BRIEF.yaml [--provider auto] [--model flash]
    ux_image.py prompt BRIEF.yaml [--option A]
    ux_image.py verify comp.png [--contract PATH]
    ux_image.py providers

Exit codes: 0 fine, 2 findings (drift, or a brief that cannot be rendered),
3 no generation provider is reachable (a real NOT_RUN, never a silent no-op).
"""
from __future__ import annotations
import argparse
import base64
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import date
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import yaml                                                        # noqa: E402
import uxconfig                                                    # noqa: E402
import pngread                                                     # noqa: E402
import palette as pal                                              # noqa: E402

MEDIUMS = ("flat", "plate", "mixed")
RATIOS = {"1:1": 1.0, "4:5": 0.8, "5:4": 1.25, "3:4": 0.75, "4:3": 4 / 3,
          "2:3": 2 / 3, "3:2": 1.5, "9:16": 0.5625, "16:9": 16 / 9, "21:9": 21 / 9}


# ---------------------------------------------------------------- the contract
class Contract:
    """The declared world, with every blank kept as a blank.

    A comp rendered from placeholder values while claiming to render the contract
    is the same laundering as a PASS on an unrun check, so `declared` records what
    was actually declared and every consumer can ask."""

    NEUTRAL = {"canvas": "#fbfbfa", "surface": "#ffffff", "ink": "#16181d",
               "muted": "#6b7280", "interactive": "#2f6fed", "focus": "#2f6fed",
               "success": "#16794a", "warning": "#9a6400", "danger": "#b42318"}

    def __init__(self, data: dict | None):
        self.raw = data or {}
        self.declared = set()
        c = (self.raw.get("color") or {}) if isinstance(self.raw.get("color"), dict) else {}
        roles = (c.get("roles") or {}) if isinstance(c.get("roles"), dict) else {}
        self.roles = {}
        for k, v in self.NEUTRAL.items():
            got = roles.get(k)
            if isinstance(got, str) and got.strip() and got.strip() != "UNKNOWN":
                self.roles[k] = got.strip()
                self.declared.add(f"color.roles.{k}")
            else:
                self.roles[k] = v
        t = (self.raw.get("type") or {}) if isinstance(self.raw.get("type"), dict) else {}
        fam = (t.get("families") or {}) if isinstance(t.get("families"), dict) else {}
        self.families = {}
        for k, dflt in (("display", "Georgia, serif"),
                        ("body", "system-ui, sans-serif"),
                        ("mono", "ui-monospace, monospace")):
            got = fam.get(k)
            if isinstance(got, str) and got.strip() and got.strip() not in ("UNKNOWN", "null"):
                self.families[k] = got.strip()
                self.declared.add(f"type.families.{k}")
            else:
                self.families[k] = dflt
        scale = t.get("scale_px")
        self.scale = sorted(float(x) for x in scale) if isinstance(scale, list) and scale \
            else [12.0, 14.0, 16.0, 20.0, 26.0, 34.0, 46.0, 62.0]
        if isinstance(scale, list) and scale:
            self.declared.add("type.scale_px")
        r = (self.raw.get("radius") or {}) if isinstance(self.raw.get("radius"), dict) else {}
        self.r_control = _px(r.get("control_px"), 8)
        self.r_card = _px(r.get("card_px"), 14)
        if _px(r.get("card_px"), None) is not None:
            self.declared.add("radius")
        d = (self.raw.get("depth") or {}) if isinstance(self.raw.get("depth"), dict) else {}
        self.depth = d.get("metaphor") if d.get("metaphor") not in (None, "", "UNKNOWN") \
            else "border"
        if d.get("metaphor") not in (None, "", "UNKNOWN"):
            self.declared.add("depth.metaphor")
        self.visitor_mode = self.raw.get("visitor_mode") \
            if self.raw.get("visitor_mode") not in (None, "", "UNKNOWN") else None
        if self.visitor_mode:
            self.declared.add("visitor_mode")
        self.world = self.raw.get("world") \
            if self.raw.get("world") not in (None, "", "UNKNOWN") else None
        if self.world:
            self.declared.add("world")
        g = (self.raw.get("grid") or {}) if isinstance(self.raw.get("grid"), dict) else {}
        self.container = _px(g.get("container_max_px"), 1200)

    def rung(self, which: str) -> float:
        """A size by job, taken from the declared ladder rather than invented."""
        s = self.scale
        if which == "display":
            return s[-1]
        if which == "title":
            return s[max(0, len(s) - 3)]
        if which == "body":
            return min(s, key=lambda v: abs(v - 16))
        if which == "small":
            return min(s, key=lambda v: abs(v - 13))
        return min(s, key=lambda v: abs(v - 16))

    def sha(self) -> str:
        """Content-addressed, so the same declaration hashes the same anywhere.

        Keys beginning with `_` are excluded because `uxconfig.contract()` adds
        `_path`, the contract's absolute location. Including it made the hash
        change when a project was cloned to a different directory -- so a comp
        and a decision recorded on two machines disagreed about which contract
        they were made against, having been made against the same one. A
        fingerprint that depends on the filing cabinet is not a fingerprint."""
        body = {k: v for k, v in self.raw.items() if not str(k).startswith("_")}
        return hashlib.sha256(
            yaml.safe_dump(body, sort_keys=True).encode()).hexdigest()[:16]

    @property
    def undeclared(self) -> list:
        want = {"visitor_mode", "world", "type.families.display", "type.families.body",
                "type.scale_px", "color.roles.canvas", "color.roles.ink",
                "color.roles.interactive", "radius", "depth.metaphor"}
        return sorted(want - self.declared)


def _px(v, default):
    try:
        return float(re.sub(r"[^0-9.]", "", str(v)))
    except (TypeError, ValueError):
        return default


def load_contract(explicit: str | None = None) -> Contract:
    return Contract(uxconfig.contract(Path.cwd(), explicit))


# --------------------------------------------------------------------- briefs
DEFAULT_OPTIONS = [
    ("A", "Imagery leads", "whether the picture or the facts carry the first screen",
     [("nav", "flat", 0.07, "brand, four links, account"),
      ("hero", "plate", 0.46, "one photograph, one headline over it"),
      ("facts", "flat", 0.30, "price, three specs, six detail rows"),
      ("act", "flat", 0.17, "one primary action, one secondary")]),
    ("B", "Facts lead", "the same content with the decision data first",
     [("nav", "flat", 0.07, "brand, four links, account"),
      ("summary", "flat", 0.26, "headline, price, three specs, one primary action"),
      ("gallery", "plate", 0.34, "four photographs in a row"),
      ("detail", "flat", 0.33, "eight detail rows, one map")]),
    ("C", "One column, dense", "whether density or breathing room suits the task",
     [("nav", "flat", 0.06, "brand, four links, account"),
      ("head", "flat", 0.14, "headline, price inline, three specs inline"),
      ("body", "mixed", 0.62, "photograph beside twelve detail rows"),
      ("act", "flat", 0.18, "one primary action, notes")]),
]


def scaffold(surface: str, n: int, viewport: list, question: str | None) -> dict:
    opts = []
    for oid, title, decides, regions in DEFAULT_OPTIONS[:max(1, min(3, n))]:
        opts.append({"id": oid, "title": title, "decides": decides,
                     "regions": [{"name": rn, "medium": rm, "share": rs, "holds": rh}
                                 for rn, rm, rs, rh in regions]})
    return {
        "question": question or f"Which structure for the {surface}?",
        "surface": surface,
        "viewport": viewport,
        "note": ("Edit this before rendering. The regions are the structural claim "
                 "the comp makes -- `share` is the vertical proportion, `medium` is "
                 "whether the band ships as code (flat) or as a raster (plate). A "
                 "band you write as flat and build as an image, or the reverse, is "
                 "the design changing after approval."),
        "options": opts,
    }


def validate(brief: dict) -> list:
    errs = []
    if not isinstance(brief.get("options"), list) or not brief["options"]:
        return ["the brief declares no options; a single comp invites a rubber stamp "
                "and two is the minimum that makes a decision possible"]
    vp = brief.get("viewport") or [1440, 900]
    if not (isinstance(vp, list) and len(vp) == 2):
        errs.append("viewport must be [width, height] in CSS px")
    seen = set()
    for o in brief["options"]:
        oid = str(o.get("id") or "")
        if not oid:
            errs.append("an option has no id")
        if oid in seen:
            errs.append(f"duplicate option id {oid}")
        seen.add(oid)
        regs = o.get("regions") or []
        if not regs:
            errs.append(f"option {oid} declares no regions, so it makes no structural "
                        f"claim and there is nothing to compare")
            continue
        for r in regs:
            if r.get("medium") not in MEDIUMS:
                errs.append(f"option {oid} region {r.get('name')}: medium "
                            f"{r.get('medium')!r} is not one of {', '.join(MEDIUMS)}")
        tot = sum(float(r.get("share") or 0) for r in regs)
        if not 0.85 <= tot <= 1.15:
            errs.append(f"option {oid} region shares total {tot:.2f}; they describe the "
                        f"whole surface so they should total about 1.0")
    return errs


def brief_sha(brief: dict) -> str:
    return hashlib.sha256(
        yaml.safe_dump(brief, sort_keys=True).encode()).hexdigest()[:16]


# ------------------------------------------------------------- SVG rendering
def esc(s) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


NUMWORD = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
           "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12}


def parts_of(holds: str) -> list:
    """What the region holds, split into the things it holds.

    Never lorem: CONTENT-003 bans placeholder copy shipping, and a comp captioned
    in Latin cannot be read for whether the hierarchy works. The brief's own words
    are the copy, which also means a reviewer can see that the region was
    described rather than guessed at."""
    out = [x.strip() for x in re.split(r"[,;]| and ", str(holds or "")) if x.strip()]
    return out or ["content"]


def counted(part: str) -> tuple[int, str]:
    """(how many, what to call one of them) for a phrase like `six detail rows`.

    A brief says "six detail rows" because six is the structural claim. Drawing one
    row labelled "Six detail rows", or six rows all labelled that, both lose it --
    the first understates the density and the second reads as a bug."""
    m = re.match(r"^\s*(\d+|" + "|".join(NUMWORD) + r")\s+(.*)$", part.strip(), re.I)
    if not m:
        return 1, part.strip()
    raw = m.group(1).lower()
    n = int(raw) if raw.isdigit() else NUMWORD[raw]
    label = re.sub(r"s$", "", m.group(2).strip()) or part.strip()
    return max(1, min(24, n)), label


def title_of(part: str) -> str:
    s = str(part).strip()
    return s[:1].upper() + s[1:]


def words(holds: str, n: int) -> list:
    """n labels, without inventing repetition where the brief named fewer things."""
    ps = [title_of(x) for x in parts_of(holds)]
    while len(ps) < n:
        ps.append("")
    return ps[:n]


def _mix(a: str, b: str, t: float) -> str:
    """Blend two hex colours. Used only for placeholder plate fills, where the
    point is to look unlike the flat regions rather than to look like a photo."""
    try:
        ar, ag, ab = (int(a.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
        br, bg, bb = (int(b.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    except (ValueError, IndexError):
        return a
    return "#%02x%02x%02x" % (round(ar + (br - ar) * t), round(ag + (bg - ag) * t),
                              round(ab + (bb - ab) * t))


class Sheet:
    """One comp sheet: the surface at its own viewport, plus the region table.

    The table is not decoration. A comp shown without its structural claim gets
    approved for its atmosphere, and then the claim -- which is the part the build
    has to honour -- was never actually agreed to."""

    CAPTION_H = 150

    def __init__(self, c: Contract, brief: dict, option: dict):
        self.c, self.brief, self.o = c, brief, option
        # Whether the surface's own title has been drawn. Without this the plate
        # band repeats the headline the summary region already carried, which
        # reads as two h1s -- a real defect in a built page (A11Y-011) and a
        # misleading one in a comp.
        self.headline_used = False
        vp = brief.get("viewport") or [1440, 900]
        self.w, self.h = int(vp[0]), int(vp[1])
        self.parts = []

    # ---- primitives
    def rect(self, x, y, w, h, fill, r=0, stroke=None, sw=1, opacity=None):
        o = f' opacity="{opacity}"' if opacity is not None else ""
        s = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
        self.parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{max(0, w):.1f}" '
                          f'height="{max(0, h):.1f}" rx="{r:.1f}" fill="{fill}"{s}{o}/>')

    def text(self, x, y, s, size, fill, family="body", weight=400, anchor="start",
             opacity=None):
        fam = self.c.families.get(family, self.c.families["body"])
        op = f' opacity="{opacity}"' if opacity is not None else ""
        self.parts.append(
            f'<text x="{x:.1f}" y="{y:.1f}" font-family="{esc(fam)}" '
            f'font-size="{size:.1f}" font-weight="{weight}" fill="{fill}" '
            f'text-anchor="{anchor}"{op}>{esc(s)}</text>')

    def line(self, x1, y1, x2, y2, stroke, sw=1):
        self.parts.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" '
                          f'y2="{y2:.1f}" stroke="{stroke}" stroke-width="{sw}"/>')

    def bar(self, x, y, w, h, fill, r=2, opacity=0.85):
        self.rect(x, y, w, h, fill, r=r, opacity=opacity)

    def card(self, x, y, w, h):
        c = self.c
        if c.depth == "shadow":
            self.rect(x, y + 2, w, h, c.roles["ink"], r=c.r_card, opacity=0.08)
            self.rect(x, y, w, h, c.roles["surface"], r=c.r_card)
        else:
            self.rect(x, y, w, h, c.roles["surface"], r=c.r_card,
                      stroke=_mix(c.roles["canvas"], c.roles["ink"], 0.14), sw=1)

    def button(self, x, y, w, h, label, primary=True):
        c = self.c
        fill = c.roles["interactive"] if primary else c.roles["surface"]
        self.rect(x, y, w, h, fill, r=c.r_control,
                  stroke=None if primary else _mix(c.roles["canvas"], c.roles["ink"], 0.22))
        ink = "#ffffff" if primary else c.roles["ink"]
        self.text(x + w / 2, y + h / 2 + c.rung("small") * 0.36, label,
                  c.rung("small"), ink, weight=600, anchor="middle")

    # ---- region painters, dispatched on what the region holds
    def band(self, y, bh, reg):
        name = str(reg.get("name") or "")
        holds = str(reg.get("holds") or "")
        medium = reg.get("medium")
        key = f"{name} {holds}".lower()
        if medium in ("plate", "mixed"):
            return self.plate(y, bh, reg, mixed=(medium == "mixed"))
        if re.search(r"\bnav|header|top ?bar|menu\b", key):
            return self.nav(y, bh, holds)
        if re.search(r"\bfoot(er)?\b", key):
            return self.footer(y, bh, holds)
        # A region that leads with a headline is a headline region even when it
        # also lists rows. Checking the rows pattern first turned every summary
        # band into a table and silently deleted the page's own title.
        if re.match(r"\s*(?:headline|title|heading|h1)\b",
                    str(holds or "").strip(), re.I) or \
                re.search(r"\bhead(line|er)?\b", name.lower()):
            return self.headline(y, bh, holds)
        if re.search(r"\brows?|specs?|detail|table|fields?|list\b", key):
            return self.rows(y, bh, holds)
        if re.search(r"\bcards?|grid|tiles?|gallery\b", key):
            return self.cards(y, bh, holds)
        if re.search(r"\bact\b|action|cta|button|enquir|submit|checkout\b", key):
            return self.act(y, bh, holds)
        return self.prose(y, bh, name, holds)

    def pad(self):
        return max(24.0, min(72.0, self.w * 0.045))

    def nav(self, y, bh, holds):
        c = self.c
        self.rect(0, y, self.w, bh, c.roles["surface"])
        self.line(0, y + bh, self.w, y + bh,
                  _mix(c.roles["canvas"], c.roles["ink"], 0.12))
        p, mid = self.pad(), y + bh / 2
        s = c.rung("small")
        ps = parts_of(holds)
        brand = title_of(ps[0]) if ps else "Brand"
        self.rect(p, mid - s * 0.7, s * 1.4, s * 1.4, c.roles["ink"], r=c.r_control * 0.5)
        self.text(p + s * 2.1, mid + s * 0.36, brand, s, c.roles["ink"], weight=600)
        # Items right to left. A part that states a count ("four links") is drawn
        # as that many unnamed items, because the count is the claim and the names
        # are not decided yet -- repeating the phrase four times says neither.
        x = self.w - p
        for part in reversed(ps[1:]):
            n, label = counted(part)
            if n > 1:
                for _ in range(n):
                    bw = s * 3.2
                    self.bar(x - bw, mid - s * 0.34, bw, s * 0.68, c.roles["muted"],
                             r=s * 0.2, opacity=0.45)
                    x -= bw + s * 1.1
            else:
                lab = title_of(label)
                self.text(x, mid + s * 0.36, lab, s, c.roles["muted"], anchor="end")
                x -= len(lab) * s * 0.55 + s * 1.6

    def plate(self, y, bh, reg, mixed=False):
        """A photographic region, drawn so it cannot be mistaken for a flat one.

        The whole reason `medium` is in the brief is that a band of pixels and a
        band of CSS are different deliverables, and the moment a plate is drawn
        as a gradient somebody builds it as a gradient."""
        c, holds = self.c, str(reg.get("holds") or "")
        a = _mix(c.roles["canvas"], c.roles["ink"], 0.72)
        b = _mix(c.roles["interactive"], c.roles["ink"], 0.45)
        gid = f"g{abs(hash((y, bh, holds))) % 99999}"
        self.parts.append(
            f'<defs><linearGradient id="{gid}" x1="0" y1="0" x2="1" y2="1">'
            f'<stop offset="0" stop-color="{a}"/>'
            f'<stop offset="1" stop-color="{b}"/></linearGradient>'
            f'<pattern id="h{gid}" width="14" height="14" patternTransform="rotate(45)" '
            f'patternUnits="userSpaceOnUse">'
            f'<line x1="0" y1="0" x2="0" y2="14" stroke="{c.roles["canvas"]}" '
            f'stroke-width="2" opacity="0.18"/></pattern></defs>')
        w = self.w if not mixed else self.w * 0.56
        self.rect(0, y, w, bh, f"url(#{gid})")
        self.rect(0, y, w, bh, f"url(#h{gid})")
        s = self.c.rung("small")
        self.text(self.pad(), y + bh - s * 1.4,
                  ("MIXED" if mixed else "PLATE") + f" · ships as a raster · {holds}",
                  s * 0.92, c.roles["canvas"], family="mono", opacity=0.9)
        if mixed:
            rest = [x for x in parts_of(holds)
                    if not re.search(r"photo|image|picture|render|video", x, re.I)]
            self.rows(y, bh, ", ".join(rest) or holds,
                      x0=w + self.pad() * 0.6, x1=self.w - self.pad())
        elif not self.headline_used:
            self.text(self.pad(), y + bh * 0.52, self.headline_text(),
                      min(c.rung("display"), bh * 0.32),
                      c.roles["canvas"], family="display", weight=600)

    def rowplan(self, holds, n_max) -> list:
        """One entry per row: its label, or None for a row the count implies."""
        plan = []
        for part in parts_of(holds):
            n, label = counted(part)
            plan.append(title_of(label))
            plan.extend([None] * (n - 1))
        return plan[:n_max] or ["Content"]

    def rows(self, y, bh, holds, x0=None, x1=None):
        c = self.c
        x0 = self.pad() if x0 is None else x0
        x1 = (self.w - self.pad()) if x1 is None else x1
        s, sm = c.rung("body"), c.rung("small")
        n = max(2, min(16, int((bh - s * 1.4) // (s * 1.7))))
        plan = self.rowplan(holds, n)
        yy = y + s * 1.6
        for i, label in enumerate(plan):
            if label:
                self.text(x0, yy, label, sm, c.roles["muted"])
            else:
                self.bar(x0, yy - sm * 0.78, (x1 - x0) * 0.22, sm * 0.72,
                         c.roles["muted"], opacity=0.32)
            self.bar(x1 - (x1 - x0) * 0.26, yy - sm * 0.8, (x1 - x0) * 0.26, sm * 0.9,
                     c.roles["ink"], opacity=0.5)
            if i < len(plan) - 1:
                self.line(x0, yy + sm * 0.9, x1, yy + sm * 0.9,
                          _mix(c.roles["canvas"], c.roles["ink"], 0.10))
            yy += s * 1.7

    def headline(self, y, bh, holds):
        """The page's own title, its supporting facts, and one action.

        Drawn as a band rather than a table because a summary region's job is to
        answer "what is this and what does it cost" before any detail."""
        c = self.c
        p = self.pad()
        ps = parts_of(holds)
        ttl = min(c.rung("display") * 0.72, bh * 0.42)
        self.text(p, y + p * 0.7 + ttl, self.headline_text(), ttl, c.roles["ink"],
                  family="display", weight=600)
        s, sm = c.rung("body"), c.rung("small")
        yy = y + p * 0.7 + ttl + s * 1.5
        x = p
        has_button = bh - (yy - y) > s * 3
        meta = ps[1:-1] if (has_button and len(ps) > 2) else ps[1:]
        for part in meta[:5]:
            n, label = counted(part)
            lab = title_of(label) + (f" \u00d7{n}" if n > 1 else "")
            self.text(x, yy, lab, sm, c.roles["muted"])
            x += len(lab) * sm * 0.62 + sm * 2.2
        if bh - (yy - y) > s * 3:
            self.button(p, yy + s * 0.9, max(150.0, self.w * 0.14),
                        max(40.0, s * 2.6), title_of(ps[-1])[:22], primary=True)

    def headline_text(self) -> str:
        self.headline_used = True
        return title_of(self.brief.get("surface") or "This screen")

    def cards(self, y, bh, holds):
        c = self.c
        p = self.pad()
        n = 4 if self.w >= 900 else 2
        gap = p * 0.5
        cw = (self.w - p * 2 - gap * (n - 1)) / n
        ch = min(bh - p, bh * 0.82)
        base = parts_of(holds)
        labels = [title_of(base[i % len(base)]) if len(base) > 1 else
                  f"{title_of(counted(base[0])[1])} {i + 1}" for i in range(n)]
        for i in range(n):
            x = p + i * (cw + gap)
            self.card(x, y + p * 0.35, cw, ch)
            self.rect(x + cw * 0.06, y + p * 0.35 + ch * 0.08, cw * 0.88, ch * 0.44,
                      _mix(c.roles["canvas"], c.roles["ink"], 0.18), r=c.r_control)
            self.text(x + cw * 0.06, y + p * 0.35 + ch * 0.66, labels[i],
                      c.rung("body"), c.roles["ink"], weight=600)
            self.bar(x + cw * 0.06, y + p * 0.35 + ch * 0.74, cw * 0.7,
                     c.rung("small") * 0.6, c.roles["muted"], opacity=0.5)

    def act(self, y, bh, holds):
        c = self.c
        p = self.pad()
        ps = parts_of(holds)
        labels = [title_of(ps[0]), title_of(ps[1]) if len(ps) > 1 else ""]
        bw = max(140.0, self.w * 0.14)
        bhh = max(40.0, c.rung("body") * 2.8)
        yy = y + (bh - bhh) / 2
        self.button(p, yy, bw, bhh, labels[0][:22], primary=True)
        if labels[1]:
            self.button(p + bw + p * 0.4, yy, bw * 0.9, bhh, labels[1][:22],
                        primary=False)

    def prose(self, y, bh, name, holds):
        c = self.c
        p = self.pad()
        ttl = min(c.rung("title"), bh * 0.34)
        self.text(p, y + p * 0.9 + ttl, title_of(parts_of(holds)[0]), ttl,
                  c.roles["ink"], family="display", weight=600)
        s = c.rung("body")
        measure = min(self.w - p * 2, self.c.container * 0.62)
        yy = y + p * 0.9 + ttl + s * 2.0
        i = 0
        while yy < y + bh - s and i < 8:
            w = measure * (1.0 if i % 3 else 0.72)
            self.bar(p, yy - s * 0.7, w, s * 0.62, c.roles["ink"], opacity=0.34)
            yy += s * 1.6
            i += 1

    def footer(self, y, bh, holds):
        c = self.c
        self.rect(0, y, self.w, bh, _mix(c.roles["canvas"], c.roles["ink"], 0.06))
        s = c.rung("small")
        self.text(self.pad(), y + bh / 2 + s * 0.36, " · ".join(words(holds, 4)),
                  s, c.roles["muted"])

    # ---- the sheet
    def svg(self) -> str:
        c, o = self.c, self.o
        regs = o.get("regions") or []
        total = sum(float(r.get("share") or 0) for r in regs) or 1.0
        self.rect(0, 0, self.w, self.h, c.roles["canvas"])
        y = 0.0
        for r in regs:
            bh = self.h * (float(r.get("share") or 0) / total)
            self.band(y, bh, r)
            y += bh
        comp = "\n".join(self.parts)

        # caption block, outside the surface
        cap, sm = [], c.rung("small")
        capy = self.h
        cap.append(f'<rect x="0" y="{capy}" width="{self.w}" height="{self.CAPTION_H}" '
                   f'fill="{_mix(c.roles["canvas"], c.roles["ink"], 0.04)}"/>')
        cap.append(f'<line x1="0" y1="{capy}" x2="{self.w}" y2="{capy}" '
                   f'stroke="{_mix(c.roles["canvas"], c.roles["ink"], 0.2)}"/>')
        fam = esc(c.families["mono"])
        ttl = f'{o.get("id")} — {o.get("title") or ""}'
        cap.append(f'<text x="{self.pad():.0f}" y="{capy + 30}" font-family="'
                   f'{esc(c.families["display"])}" font-size="{sm * 1.5:.0f}" '
                   f'font-weight="600" fill="{c.roles["ink"]}">{esc(ttl)}</text>')
        cap.append(f'<text x="{self.pad():.0f}" y="{capy + 52}" font-family="{fam}" '
                   f'font-size="{sm * 0.92:.0f}" fill="{c.roles["muted"]}">'
                   f'{esc("decides: " + str(o.get("decides") or "unstated"))}</text>')
        rowy = capy + 78
        for r in regs[:5]:
            share = float(r.get("share") or 0) / total
            txt = (f'{r.get("name"):<12} {r.get("medium"):<6} {share * 100:4.0f}%  '
                   f'{str(r.get("holds") or "")[:70]}')
            cap.append(f'<text x="{self.pad():.0f}" y="{rowy}" font-family="{fam}" '
                       f'font-size="{sm * 0.85:.0f}" fill="{c.roles["ink"]}" '
                       f'xml:space="preserve">{esc(txt)}</text>')
            rowy += sm * 1.35
        und = c.undeclared
        note = (f'rendered from the contract ({len(c.declared)} fields declared)'
                if not und else
                f'{len(und)} contract fields are UNDECLARED and drawn with '
                f'placeholders: {", ".join(und[:4])}')
        cap.append(f'<text x="{self.w - self.pad():.0f}" y="{capy + 30}" '
                   f'font-family="{fam}" font-size="{sm * 0.85:.0f}" '
                   f'fill="{"#b42318" if und else c.roles["muted"]}" '
                   f'text-anchor="end">{esc(note)}</text>')
        return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" '
                f'height="{self.h + self.CAPTION_H}" viewBox="0 0 {self.w} '
                f'{self.h + self.CAPTION_H}">\n'
                f'<title>{esc(self.brief.get("surface") or "comp")} — {esc(ttl)}</title>\n'
                f'{comp}\n' + "\n".join(cap) + "\n</svg>\n")


# -------------------------------------------------------------- prompt from it
# What the visitor came to do, said as what they are doing rather than as the
# mode's label. "The visitor came to persuade" inverts the relationship: the
# product persuades, the visitor decides.
VISITOR_SENTENCE = {
    "persuade": "The visitor is deciding whether to trust this and has not committed "
                "to anything yet.",
    "experience": "The visitor came for the thing itself; the interface is the frame "
                  "around it, not the subject.",
    "operate": "The visitor came to get a specific job done and will be back "
               "tomorrow to do it again.",
    "read": "The visitor came to read, at length, and everything else is an "
            "interruption.",
    "native": "The visitor is on a phone and expects the platform's own patterns.",
}


def build_prompt(c: Contract, brief: dict, option: dict) -> str:
    regs = option.get("regions") or []
    total = sum(float(r.get("share") or 0) for r in regs) or 1.0
    vp = brief.get("viewport") or [1440, 900]
    lines = []
    lines.append(f"A high-fidelity interface design comp of a {brief.get('surface')} "
                 f"screen, {int(vp[0])}x{int(vp[1])}, "
                 f"{'portrait' if vp[1] > vp[0] else 'landscape'}.")
    lines.append("")
    lines.append("Regions, top to bottom, with the vertical share each occupies. "
                 "Lead with these: the surface's structure is the subject, and the "
                 "content is what the regions hold.")
    for r in regs:
        share = float(r.get("share") or 0) / total
        med = {"flat": "flat, drawn in the interface's own colours",
               "plate": "a photographic plate -- a real photograph, not an "
                        "illustration or a gradient",
               "mixed": "half photographic plate, half flat interface"}.get(
                   r.get("medium"), "flat")
        lines.append(f"  - {r.get('name')} — {share * 100:.0f}% of the height, "
                     f"{med}. Holds: {r.get('holds')}.")
    lines.append("")
    if c.world:
        lines.append(f"The world, already committed and not up for reinterpretation: "
                     f"{c.world}")
    if c.visitor_mode:
        lines.append(f"{VISITOR_SENTENCE.get(c.visitor_mode, 'The visitor mode is ' + str(c.visitor_mode) + '.')} "
                     f"That must be readable from the image with no caption.")
    lines.append(f"Palette, exactly these values and no others: canvas "
                 f"{c.roles['canvas']}, surface {c.roles['surface']}, ink "
                 f"{c.roles['ink']}, muted text {c.roles['muted']}, the single accent "
                 f"{c.roles['interactive']}.")
    lines.append(f"Typography: {c.families['display']} for display, "
                 f"{c.families['body']} for text. Sizes on the ladder "
                 f"{', '.join(f'{x:g}' for x in c.scale)}px; the largest type on the "
                 f"screen is about {c.rung('display'):g}px.")
    lines.append(f"Corner radius {c.r_card:g}px on cards, {c.r_control:g}px on "
                 f"controls. Depth is expressed with "
                 f"{'one soft shadow set' if c.depth == 'shadow' else 'hairline borders'} "
                 f"and nothing else -- never both.")
    lines.append(f"One dominant move: {option.get('decides') or option.get('title')}. "
                 f"Everything else holds still so it can be read. Two things "
                 f"competing at the same scale is shouting.")
    lines.append("")
    lines.append("Do not include: a browser chrome frame, a device mockup or bezel, a "
                 "drop-shadowed floating card over a gradient mesh, lorem ipsum, "
                 "watermarks, a logo of any real company, three-quarter perspective, "
                 "or a dark overlay used to rescue text contrast.")
    lines.append("Text in the image is indicative only. The built screen renders real "
                 "text -- so the comp must not depend on any text being legible at a "
                 "size the type ladder does not contain.")
    if c.undeclared:
        lines.append("")
        lines.append("NOTE for the reader, not for the model: "
                     + f"{len(c.undeclared)} contract fields are undeclared "
                     + f"({', '.join(c.undeclared)}), so this prompt carries "
                     + "placeholders for them. What comes back is not evidence about "
                     + "those fields.")
    return "\n".join(lines)


def nearest_ratio(w: int, h: int) -> str:
    want = w / max(1, h)
    return min(RATIOS, key=lambda k: abs(math.log(RATIOS[k] / want)))


# ------------------------------------------------------------------ providers
def _nb_script() -> Path | None:
    env = os.environ.get("DELUXUI_NB_GENERATE")
    if env and Path(env).is_file():
        return Path(env)
    # Installed as a sibling skill, which is how both of these ship.
    for cand in (HERE.parent.parent / "image-nanobanana" / "scripts" / "nb-generate.py",
                 Path.home() / ".agents" / "skills" / "image-nanobanana" / "scripts"
                 / "nb-generate.py",
                 Path.home() / ".claude" / "skills" / "image-nanobanana" / "scripts"
                 / "nb-generate.py"):
        if cand.is_file():
            return cand
    return None


def gemini_key() -> str | None:
    for k in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        if os.environ.get(k):
            return os.environ[k]
    env = Path.home() / ".gemini" / ".env"
    if env.is_file():
        for line in env.read_text(errors="replace").splitlines():
            m = re.match(r"\s*(?:export\s+)?(GEMINI_API_KEY|GOOGLE_API_KEY)\s*=\s*(.+)",
                         line)
            if m:
                return m.group(2).strip().strip("'\"") or None
    return None


def providers() -> list:
    """Every generation path, available or not, each with the reason.

    A provider that is absent has to say what would make it present, or the report
    reads as "image generation is impossible" when it is one environment variable
    away."""
    out = []
    cmd = os.environ.get("DELUXUI_IMAGE_CMD")
    out.append({
        "id": "command", "available": bool(cmd),
        "detail": (f"DELUXUI_IMAGE_CMD={cmd}" if cmd else
                   "DELUXUI_IMAGE_CMD is unset. Set it to any command that writes an "
                   "image, with {prompt} {out} {w} {h} placeholders -- this is how a "
                   "harness with its own image tool plugs in without deluxui knowing "
                   "anything about it.")})
    nb = _nb_script()
    key = gemini_key()
    out.append({
        "id": "nanobanana", "available": bool(nb and key),
        "detail": (f"{nb} with a Gemini key" if nb and key else
                   (f"{nb} is present but no GEMINI_API_KEY / GOOGLE_API_KEY was found "
                    f"(checked the environment and ~/.gemini/.env). Gemini image models "
                    f"have no free tier, so this needs a billed key."
                    if nb else
                    "the image-nanobanana skill is not installed beside this one. Set "
                    "DELUXUI_NB_GENERATE to its scripts/nb-generate.py, or install it."))})
    out.append({
        "id": "gemini", "available": bool(key),
        "detail": ("a Gemini key is present; deluxui can call the REST API directly "
                   "(v1beta generateContent, which is the surface that accepts "
                   "generationConfig.imageConfig)" if key else
                   "no GEMINI_API_KEY / GOOGLE_API_KEY in the environment or "
                   "~/.gemini/.env.")})
    ok = bool(os.environ.get("OPENAI_API_KEY"))
    out.append({
        "id": "openai", "available": ok,
        "detail": ("OPENAI_API_KEY is set; images/generations with gpt-image-1"
                   if ok else "OPENAI_API_KEY is unset.")})
    return out


def _write_image(out: Path, data: bytes) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    return out


def gen_command(prompt: str, out: Path, w: int, h: int) -> tuple[bool, str]:
    tpl = os.environ.get("DELUXUI_IMAGE_CMD") or ""
    pf = out.with_suffix(".prompt.txt")
    pf.parent.mkdir(parents=True, exist_ok=True)
    pf.write_text(prompt)
    cmd = (tpl.replace("{prompt_file}", str(pf)).replace("{prompt}", prompt)
           .replace("{out}", str(out)).replace("{w}", str(w)).replace("{h}", str(h))
           .replace("{ratio}", nearest_ratio(w, h)))
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=600)
    except (OSError, subprocess.SubprocessError) as e:
        return False, f"DELUXUI_IMAGE_CMD failed to run: {e}"
    if out.exists() and out.stat().st_size > 0:
        return True, f"DELUXUI_IMAGE_CMD wrote {out.stat().st_size} bytes"
    return False, (f"the command exited {r.returncode} and no file appeared at {out}. "
                   f"stderr: {(r.stderr or '').strip()[:300]}")


def gen_nanobanana(prompt: str, out: Path, w: int, h: int, model: str) -> tuple[bool, str]:
    nb = _nb_script()
    if not nb:
        return False, "nb-generate.py not found"
    pf = out.with_suffix(".prompt.txt")
    pf.parent.mkdir(parents=True, exist_ok=True)
    pf.write_text(prompt)
    tmp = out.parent / (out.stem + "-nb")
    cmd = [sys.executable, str(nb), "--prompt-file", str(pf), "-m", model,
           "-a", nearest_ratio(w, h), "-o", str(tmp), "--name", out.stem]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    except (OSError, subprocess.SubprocessError) as e:
        return False, f"nb-generate.py failed to run: {e}"
    got = sorted(tmp.rglob("*.png")) + sorted(tmp.rglob("*.jpg")) \
        + sorted(tmp.rglob("*.webp"))
    if got:
        _write_image(out.with_suffix(got[0].suffix), got[0].read_bytes())
        return True, f"nb-generate.py ({model}) wrote {got[0].name}"
    return False, (f"nb-generate.py exited {r.returncode} and produced no image. "
                   f"{(r.stderr or '').strip()[-400:]}")


def gen_gemini(prompt: str, out: Path, w: int, h: int, model: str) -> tuple[bool, str]:
    key = gemini_key()
    if not key:
        return False, "no Gemini key"
    mid = {"flash": "gemini-3.1-flash-image", "pro": "gemini-3-pro-image"}.get(model, model)
    base = os.environ.get("GEMINI_API_BASE_URL",
                          "https://generativelanguage.googleapis.com")
    ver = os.environ.get("GEMINI_API_VERSION", "v1beta")
    url = f"{base}/{ver}/models/{mid}:generateContent"
    payload = {"contents": [{"parts": [{"text": prompt}]}],
               "generationConfig": {"responseModalities": ["IMAGE"],
                                    "imageConfig": {"aspectRatio": nearest_ratio(w, h)}}}
    req = urllib.request.Request(
        url, data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "x-goog-api-key": key})
    try:
        with urllib.request.urlopen(req, timeout=180) as r:
            body = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        raw = e.read().decode(errors="replace")
        try:
            detail = (json.loads(raw).get("error") or {}).get("message") or raw
        except ValueError:
            detail = raw
        detail = " ".join(detail.split())[:300]
        hint = ""
        if e.code == 429:
            hint = ("\n      A 429 on a Gemini key means billing is not enabled on the "
                    "project: the image models have zero free-tier quota, so `limit: 0` "
                    "is the expected shape and retrying will not help. Enable billing "
                    "on the key's project, or set DELUXUI_IMAGE_CMD to a generator you "
                    "already pay for.")
        elif e.code == 400 and "API_KEY_INVALID" in raw:
            hint = ("\n      The key was rejected. Gemini returns 400 for this, not "
                    "401, so a 400 here is an auth problem and not a bad payload.")
        elif e.code == 404:
            hint = ("\n      The model id is not visible to this key -- check it is a "
                    "GA id (gemini-3.1-flash-image / gemini-3-pro-image) and not a "
                    "retired -preview one.")
        return False, f"HTTP {e.code}: {detail}{hint}"
    except (urllib.error.URLError, OSError, ValueError) as e:
        return False, f"request failed: {e}"
    for cand in body.get("candidates") or []:
        for part in (cand.get("content") or {}).get("parts") or []:
            inline = part.get("inlineData") or part.get("inline_data")
            if inline and inline.get("data"):
                ext = {"image/png": ".png", "image/jpeg": ".jpg",
                       "image/webp": ".webp"}.get(inline.get("mimeType")
                                                  or inline.get("mime_type"), ".png")
                _write_image(out.with_suffix(ext), base64.b64decode(inline["data"]))
                return True, f"{mid} returned {ext[1:]}"
    return False, (f"{mid} returned no image part. "
                   f"{json.dumps(body)[:300]}")


def gen_openai(prompt: str, out: Path, w: int, h: int, model: str) -> tuple[bool, str]:
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        return False, "OPENAI_API_KEY is unset"
    size = "1536x1024" if w > h else ("1024x1536" if h > w else "1024x1024")
    payload = {"model": "gpt-image-1", "prompt": prompt[:4000], "size": size, "n": 1}
    req = urllib.request.Request(
        "https://api.openai.com/v1/images/generations",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {key}"})
    try:
        with urllib.request.urlopen(req, timeout=240) as r:
            body = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return False, f"HTTP {e.code}: {e.read().decode(errors='replace')[:300]}"
    except (urllib.error.URLError, OSError, ValueError) as e:
        return False, f"request failed: {e}"
    for d in body.get("data") or []:
        if d.get("b64_json"):
            _write_image(out.with_suffix(".png"), base64.b64decode(d["b64_json"]))
            return True, "gpt-image-1 returned png"
        if d.get("url"):
            try:
                with urllib.request.urlopen(d["url"], timeout=180) as r:
                    _write_image(out.with_suffix(".png"), r.read())
                return True, "gpt-image-1 returned a url, fetched"
            except (urllib.error.URLError, OSError) as e:
                return False, f"could not fetch the returned url: {e}"
    return False, "no image in the response"


GENERATORS = {"command": gen_command, "nanobanana": gen_nanobanana,
              "gemini": gen_gemini, "openai": gen_openai}


def generate_one(prov: str, prompt: str, out: Path, w: int, h: int,
                 model: str) -> tuple[bool, str]:
    fn = GENERATORS[prov]
    if prov == "command":
        return fn(prompt, out, w, h)
    return fn(prompt, out, w, h, model)


# --------------------------------------------------------------------- verify
def _oklab(rgb) -> tuple:
    L, C, H = pal.rgb_to_oklch(tuple(rgb))
    return (L, C * math.cos(math.radians(H)), C * math.sin(math.radians(H)))


def _de(a, b) -> float:
    la, aa, ba = _oklab(a)
    lb, ab, bb = _oklab(b)
    return math.sqrt((la - lb) ** 2 + (aa - ab) ** 2 + (ba - bb) ** 2)


def _hex_rgb(s: str):
    s = str(s or "").strip()
    m = re.fullmatch(r"#?([0-9a-fA-F]{6})", s)
    if m:
        v = m.group(1)
        return tuple(int(v[i:i + 2], 16) for i in (0, 2, 4))
    m = re.fullmatch(r"#?([0-9a-fA-F]{3})", s)
    if m:
        return tuple(int(c * 2, 16) for c in m.group(1))
    m = re.match(r"rgba?\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)", s)
    if m:
        return tuple(int(m.group(i)) for i in (1, 2, 3))
    return None


# A role is "present" when some colour covering a real share of the image is
# within this distance of it in OKLab. 0.035 is about where two swatches stop
# reading as the same colour on screen.
#
# The palette read is quantised, so a flat tolerance has to be loose enough to
# absorb the quantiser -- and a tolerance loose enough for that let a cool grey
# #e8e8f8 pass as the declared warm paper #faf7f2, which is precisely the drift
# this check exists to catch. So the quantiser's own error is computed per colour
# (the declared value, put through the same bucketing) and added, instead of being
# guessed at once for every colour.
ROLE_TOL = 0.035
QUANT = 3                 # 32 levels per channel; comp_spec's default is coarser


def _quantised(rgb) -> tuple:
    mul = 1 << QUANT
    return tuple(min(255, (int(c) >> QUANT) * mul + mul // 2) for c in rgb)


def tolerance_for(rgb) -> float:
    """The distance below which a difference is the quantiser, not the design."""
    return round(ROLE_TOL + _de(rgb, _quantised(rgb)), 4)


# Near-neutral colours sit close together in OKLab whatever their tint, so a warm
# paper canvas and a cool grey one are a small Euclidean distance apart -- and
# they are completely different worlds. Direction is checked separately from
# distance for exactly that reason: the tint IS the design decision, and it is
# the first thing a generator throws away.
TINT_FLOOR = 0.004


def tint_flipped(want, got) -> bool:
    _lw, aw, bw = _oklab(want)
    _lg, ag, bg = _oklab(got)
    if math.hypot(aw, bw) < TINT_FLOOR or math.hypot(ag, bg) < TINT_FLOOR:
        return False                     # one of them is genuinely neutral
    return (aw * ag + bw * bg) <= 0.0    # pointing the other way round the wheel


def tint_name(rgb) -> str:
    _l, a, b = _oklab(rgb)
    if math.hypot(a, b) < TINT_FLOOR:
        return "neutral"
    deg = math.degrees(math.atan2(b, a)) % 360
    for lo, hi, nm in ((20, 80, "warm/yellow"), (80, 160, "green"),
                       (160, 250, "cool/blue"), (250, 330, "violet/magenta")):
        if lo <= deg < hi:
            return nm
    return "red/orange"


def verify(png: Path, c: Contract) -> dict:
    import comp_spec
    img = pngread.rows(png)
    if img is None:
        return {"ok": False, "error":
                f"{png} is not an 8-bit non-interlaced PNG. Nothing is claimed about "
                f"an image that was not decoded."}
    spec = comp_spec.analyse(img, quant=QUANT)
    pal_entries = [(tuple(p["rgb"]), p["coverage_pct"]) for p in spec["palette"]]
    findings, roles = [], {}
    for role in ("canvas", "surface", "ink", "interactive"):
        want = _hex_rgb(c.roles[role])
        declared = f"color.roles.{role}" in c.declared
        if not want:
            roles[role] = {"declared": declared, "verdict": "unparseable"}
            continue
        tol = tolerance_for(want)
        best, bestd = None, 99.0
        for rgb, cov in pal_entries:
            d = _de(want, rgb)
            if d < bestd and cov >= 0.4:
                best, bestd = (rgb, cov), d
        roles[role] = {"declared": declared, "want": c.roles[role],
                       "nearest": comp_spec.hexof(best[0]) if best else None,
                       "coverage_pct": best[1] if best else 0.0,
                       "distance": round(bestd, 4), "tolerance": tol,
                       "verdict": "present" if bestd <= tol else "absent"}
        if best and tint_flipped(want, best[0]):
            roles[role]["verdict"] = "tinted-away"
        if not declared:
            continue
        if best and roles[role]["verdict"] == "tinted-away" and bestd <= tol:
            findings.append(
                f"the {role} in this image is {comp_spec.hexof(best[0])} "
                f"({tint_name(best[0])}) where the contract declares "
                f"{c.roles[role]} ({tint_name(want)}). The numeric distance is "
                f"small ({bestd:.3f}) and the tint is the opposite way round the "
                f"wheel, which is a different world rather than a near miss -- a "
                f"warm paper ground and a cool grey one are not interchangeable, "
                f"and a comp approved in one will be built in the other.")
            continue
        if bestd > tol:
            findings.append(
                f"the declared {role} {c.roles[role]} is not in this image -- the "
                f"nearest colour covering any real area is "
                f"{comp_spec.hexof(best[0]) if best else 'nothing'} "
                f"(OKLab distance {bestd:.3f}, tolerance {tol}). A comp in a "
                f"palette the contract does not contain cannot be the thing the "
                f"build is measured against: either the comp drifted, or the "
                f"contract did and should be updated on purpose.")
    ratio = spec.get("ink_on_canvas")
    if ratio is not None and ratio < 4.5:
        findings.append(
            f"the image's own ink-on-canvas ratio is {ratio}:1, under the 4.5:1 body "
            f"text floor (NUM-001). A comp whose text contrast already fails cannot "
            f"be built as drawn, so the decision it is asking for is not a real one.")
    plate = spec["counts"]["plate"] + spec["counts"]["mixed"]
    prov = pngread.text_chunks(png) or {}
    if not prov:
        findings.append(
            "no provenance in the file. A generated comp with no record of the prompt, "
            "the model or the contract it was built from is an asset nobody can "
            "account for six weeks later -- write it with "
            "`comp_spec.py <file> --provenance ...`.")
    return {"ok": True, "image": str(png), "size": spec["size"],
            "canvas": spec["canvas"], "ink": spec["ink"], "ink_on_canvas": ratio,
            "roles": roles, "plate_bands": plate, "regions": spec["counts"],
            "provenance": sorted(prov), "contract_declared": sorted(c.declared),
            "contract_undeclared": c.undeclared, "findings": findings}


# ------------------------------------------------------------------------ CLI
def load_brief(p: str) -> dict:
    t = sys.stdin.read() if p == "-" else Path(p).read_text()
    return yaml.safe_load(t) or {}


def cmd_brief(a) -> int:
    vp = [int(x) for x in str(a.viewport).split("x")] if a.viewport else [1440, 900]
    b = scaffold(a.surface, a.options, vp, a.question)
    out = Path(a.write) if a.write else None
    text = yaml.safe_dump(b, sort_keys=False, allow_unicode=True, width=88)
    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        sys.stderr.write(f"wrote {out}\nEdit the regions before rendering: the "
                         f"defaults describe a property page, not yours.\n")
    else:
        print(text)
    return 0


def cmd_render(a) -> int:
    c = load_contract(a.contract)
    brief = load_brief(a.brief)
    errs = validate(brief)
    if errs:
        for e in errs:
            sys.stderr.write(f"  brief: {e}\n")
        return 2
    outdir = Path(a.out)
    outdir.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9]+", "-", str(brief.get("surface") or "comp").lower()).strip("-")
    made = []
    for o in brief["options"]:
        svg = Sheet(c, brief, o).svg()
        p = outdir / f"{slug}-{o['id']}.svg"
        p.write_text(svg)
        made.append(p)
    # The decision page reads this, so it carries the whole claim each option
    # makes -- not just a file path. A page that shows three pictures and no
    # structural claim collects an approval of the atmosphere, and the atmosphere
    # is not the part the build has to honour.
    meta = {"brief_sha": brief_sha(brief), "contract_sha": c.sha(),
            "contract_declared": sorted(c.declared), "contract_undeclared": c.undeclared,
            "rendered_on": str(date.today()), "renderer":
                "deluxui/ux_image.py render (deterministic, no model)",
            "question": brief.get("question"), "surface": brief.get("surface"),
            "viewport": brief.get("viewport"),
            "rendered": [str(p) for p in made],
            "options": [{"id": o["id"], "title": o.get("title"),
                         "decides": o.get("decides"),
                         "image": str(outdir / f"{slug}-{o['id']}.svg"),
                         "regions": o.get("regions") or []}
                        for o in brief["options"]]}
    (outdir / f"{slug}.comps.yaml").write_text(
        yaml.safe_dump(meta, sort_keys=False, allow_unicode=True))
    sys.stderr.write(f"\n{len(made)} comp(s) rendered from the contract:\n")
    for p in made:
        sys.stderr.write(f"  {p}\n")
    if c.undeclared:
        sys.stderr.write(
            f"\n{len(c.undeclared)} contract fields are undeclared and were drawn with "
            f"placeholders: {', '.join(c.undeclared)}.\nThose parts of the comp are "
            f"not the design -- they are what a blank looks like. Declare them first "
            f"if the comp is meant to settle them.\n")
    sys.stderr.write(f"\nNext: serve the choice --  python3 scripts/ux_question.py ask "
                     f"{outdir / (slug + '.comps.yaml')}\n")
    return 0


def cmd_prompt(a) -> int:
    c = load_contract(a.contract)
    brief = load_brief(a.brief)
    for o in brief.get("options") or []:
        if a.option and str(o.get("id")) != a.option:
            continue
        print(f"### option {o.get('id')} — {o.get('title')}\n")
        print(build_prompt(c, brief, o))
        print()
    return 0


def cmd_generate(a) -> int:
    c = load_contract(a.contract)
    brief = load_brief(a.brief)
    errs = validate(brief)
    if errs:
        for e in errs:
            sys.stderr.write(f"  brief: {e}\n")
        return 2
    provs = providers()
    avail = [p["id"] for p in provs if p["available"]]
    chosen = None
    if a.provider != "auto":
        chosen = a.provider if a.provider in avail else None
        if chosen is None:
            sys.stderr.write(f"provider {a.provider!r} is not available here.\n")
    else:
        for pref in ("command", "nanobanana", "gemini", "openai"):
            if pref in avail:
                chosen = pref
                break
    outdir = Path(a.out)
    slug = re.sub(r"[^a-z0-9]+", "-", str(brief.get("surface") or "comp").lower()).strip("-")
    vp = brief.get("viewport") or [1440, 900]

    # The rendered comps are produced either way. A generation round that fails
    # must not leave the decision with nothing to look at, and the deterministic
    # sheet is the floor this tool guarantees.
    rc = cmd_render(argparse.Namespace(brief=a.brief, out=a.out, contract=a.contract))
    if rc:
        return rc

    if not chosen:
        sys.stderr.write("\nNo image-generation provider is reachable, so no raster "
                         "was produced. This is NOT_RUN, not a failure of the comp "
                         "round -- the rendered sheets above are real comps and they "
                         "are what the decision is made on.\n\n")
        for p in provs:
            sys.stderr.write(f"  {p['id']:<12} {'yes' if p['available'] else 'no ':<4} "
                             f"{p['detail']}\n")
        return 3
    results = []
    for o in brief["options"]:
        prompt = build_prompt(c, brief, o)
        out = outdir / f"{slug}-{o['id']}.png"
        ok, note = generate_one(chosen, prompt, out, int(vp[0]), int(vp[1]), a.model)
        sys.stderr.write(f"  {o['id']}: {'ok  ' if ok else 'FAIL'} {note}\n")
        if ok:
            got = next((q for q in (out, out.with_suffix(".jpg"),
                                    out.with_suffix(".webp")) if q.exists()), None)
            if got and got.suffix == ".png":
                pngread.add_text(got, "deluxui:provenance", json.dumps({
                    "provider": chosen, "model": a.model, "option": o["id"],
                    "brief_sha": brief_sha(brief), "contract_sha": c.sha(),
                    "generated_on": str(date.today()), "prompt": prompt}, indent=1))
            results.append({"option": o["id"], "file": str(got), "provider": chosen})
    if not results:
        sys.stderr.write("\nEvery generation attempt failed. The rendered sheets "
                         "stand; the raster round is NOT_RUN.\n")
        return 3
    sys.stderr.write(f"\n{len(results)} raster(s) generated by {chosen}. Now measure "
                     f"them against the contract they claim to express:\n")
    for r in results:
        sys.stderr.write(f"  python3 scripts/ux_image.py verify {r['file']}\n")
    return 0


def cmd_verify(a) -> int:
    c = load_contract(a.contract)
    res = verify(Path(a.image), c)
    if a.json:
        print(json.dumps(res, indent=1))
    if not res.get("ok"):
        sys.stderr.write(res.get("error", "could not read the image") + "\n")
        return 2
    if not a.json:
        w = sys.stderr.write
        w(f"\ncomp conformance -- {res['image']}  {res['size'][0]}x{res['size'][1]}\n")
        w(f"canvas {res['canvas']}   ink {res['ink']}   "
          f"ink on canvas {res['ink_on_canvas']}:1\n")
        w(f"bands: {res['regions']}  (plate/mixed bands ship as rasters)\n\n")
        for role, r in res["roles"].items():
            if not r.get("declared"):
                w(f"  {role:<12} NOT_RUN   nothing declared, so nothing to conform to\n")
                continue
            w(f"  {role:<12} {r['verdict'].upper():<9} declared {r['want']}, nearest in "
              f"image {r['nearest']} (Δ {r['distance']}, {r['coverage_pct']}% cover)\n")
        if res["contract_undeclared"]:
            w(f"\n{len(res['contract_undeclared'])} contract fields undeclared: "
              f"{', '.join(res['contract_undeclared'])}\n")
        if res["findings"]:
            w(f"\n{len(res['findings'])} finding(s):\n")
            for f in res["findings"]:
                w(f"\n  - {f}\n")
        else:
            w("\nNo drift. Every declared role is present in the image at real "
              "coverage.\n")
    return 2 if res["findings"] else 0


def cmd_providers(a) -> int:
    provs = providers()
    if a.json:
        print(json.dumps(provs, indent=1))
        return 0 if any(p["available"] for p in provs) else 3
    sys.stderr.write("\nimage generation providers\n" + "=" * 70 + "\n")
    for p in provs:
        sys.stderr.write(f"\n  {p['id']:<12} {'AVAILABLE' if p['available'] else 'no'}\n"
                         f"      {p['detail']}\n")
    if not any(p["available"] for p in provs):
        sys.stderr.write(
            "\nNothing can generate a raster here. `render` still works and needs "
            "nothing: it draws the comp from the contract, which is the half of a "
            "comp round that a model was never required for.\n")
        return 3
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")

    b = sub.add_parser("brief", help="scaffold a comp brief")
    b.add_argument("--write", nargs="?", const=".deluxui/comps/comp.brief.yaml")
    b.add_argument("--surface", default="screen")
    b.add_argument("--options", type=int, default=3)
    b.add_argument("--viewport", help="WxH, e.g. 390x844")
    b.add_argument("--question")
    b.set_defaults(fn=cmd_brief)

    for name, fn, helptext in (("render", cmd_render, "draw the comps from the contract"),
                               ("generate", cmd_generate, "render, then ask a model")):
        s = sub.add_parser(name, help=helptext)
        s.add_argument("brief")
        s.add_argument("--out", default=".deluxui/comps")
        s.add_argument("--contract")
        if name == "generate":
            s.add_argument("--provider", default="auto",
                           choices=["auto", "command", "nanobanana", "gemini", "openai"])
            s.add_argument("--model", default="flash")
        s.set_defaults(fn=fn)

    p = sub.add_parser("prompt", help="the prompt built from the contract")
    p.add_argument("brief")
    p.add_argument("--option")
    p.add_argument("--contract")
    p.set_defaults(fn=cmd_prompt)

    v = sub.add_parser("verify", help="measure a comp against the contract")
    v.add_argument("image")
    v.add_argument("--contract")
    v.add_argument("--json", action="store_true")
    v.set_defaults(fn=cmd_verify)

    q = sub.add_parser("providers", help="what can generate here")
    q.add_argument("--json", action="store_true")
    q.set_defaults(fn=cmd_providers)

    a = ap.parse_args(argv)
    if not getattr(a, "fn", None):
        ap.print_help()
        return 1
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
